import type { WorkoutClass } from "@/types/health";

export const trainingClasses: WorkoutClass[] = [
  {
    id: "gym-1",
    title: "Full-body strength",
    category: "gym",
    difficulty: "Medium",
    durationMin: 35,
    muscleGroup: "Full body",
    instructions: "Warm-up 5 min, 3 rounds: squats, push-ups, rows, plank. Cool down 5 min.",
    videoUrl: "https://www.youtube.com/watch?v=example",
    caloriesEstimate: 280,
  },
  {
    id: "cardio-1",
    title: "HIIT burst",
    category: "cardio",
    difficulty: "Hard",
    durationMin: 20,
    muscleGroup: "Cardio",
    instructions: "30s work / 30s rest × 8: jumping jacks, high knees, burpees, mountain climbers.",
    caloriesEstimate: 220,
  },
  {
    id: "home-1",
    title: "Living room flow",
    category: "home",
    difficulty: "Easy",
    durationMin: 25,
    muscleGroup: "Core + legs",
    instructions: "No equipment: lunges, glute bridges, dead bug, wall sit.",
    caloriesEstimate: 150,
  },
  {
    id: "stretch-1",
    title: "Morning mobility",
    category: "stretching",
    difficulty: "Easy",
    durationMin: 15,
    muscleGroup: "Mobility",
    instructions: "Neck rolls, cat-cow, hip circles, hamstring stretch, child's pose.",
    caloriesEstimate: 60,
  },
  {
    id: "relax-1",
    title: "Stress relief stretch",
    category: "relax",
    difficulty: "Easy",
    durationMin: 12,
    muscleGroup: "Recovery",
    instructions: "Slow breathing + gentle shoulder and hip openers.",
    caloriesEstimate: 40,
  },
];
